checks = ["all", "-ST1000", "-ST1020", "-ST1021", "-ST1022"]
initialisms = ["ACL", "API", "ASCII", "CPU", "CSS", "CSV", "DNS", "DDL", "EOF", "GUID",
  "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "OID", "PID", "QPS", "RAM", "RPC", "SLA",
  "SMTP", "SQL", "SSH", "SSL", "TCP", "TLS", "TTL", "UDP", "UI", "UID", "UUID", "URI",
  "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]
